var quotes = [
  '“Words are a form of action, capable of influencing change.” <br/><span style="color:#b3b3b3 !important;">Ingrid Bengis</span>',
  '“There is nothing to writing. All you do is sit down at a typewriter and bleed.” <br/><span style="color:#b3b3b3 !important;">Ernest Hemingway</span>',
  '“Don’t bend; don’t water it down; don’t try to make it logical; don’t edit your own soul according to the fashion. Rather, follow your most intense obsessions mercilessly.” <br/><span style="color:#b3b3b3 !important;">Franz Kafka</span>',
  '“The artist is always beginning. Any work of art which is not a beginning, an invention, a discovery is of little worth.” <br/><span style="color:#b3b3b3 !important;">Ezra Pound</span>',
  '“Words are a lens to focus one’s mind.” <br/><span style="color:#b3b3b3 !important;">Ayn Rand</span>',
  '“I went for years not finishing anything. Because, of course, when you finish something you can be judged.” <br/><span style="color:#b3b3b3 !important;">Erica Jong</span>',
  '“The work never matches the dream of perfection the artist has to start with.” <br/><span style="color:#b3b3b3 !important;">William Faulkner</span>',
  '“Writing is its own reward.” <br/><span style="color:#b3b3b3 !important;">Henry Miller</span>',
  '“Only in men’s imagination does every truth find an effective and undeniable existence. Imagination, not invention, is the supreme master of art as of life.” <br/><span style="color:#b3b3b3 !important;">Joseph Conrad</span>',
  '“I don’t think there’s any artist of any value who doesn’t doubt what they’re doing.” <br/><span style="color:#b3b3b3 !important;">Francis Ford Coppola</span>',
  '“Creativity is just connecting things. When you ask creative people how they did something, they feel a little guilty because they didn’t really do it, they just saw something. It seemed obvious to them after a while. That’s because they were able to connect experiences they’ve had and synthesize new things.” <br/><span style="color:#b3b3b3 !important;">Steve Jobs</span>',
  '“Always do your best. What you plant now, you will harvest later.” <br/><span style="color:#b3b3b3 !important;">Og Mandino</span>',
  '“Imagination is more important than knowledge.” <br/><span style="color:#b3b3b3 !important;">Albert Einstein</span>',
  '“Clean out a corner of your mind and creativity will instantly fill it.” <br/><span style="color:#b3b3b3 !important;">Dee Hock</span>',
  '“Can you imagine what I would do if I could do all I can?” <br/><span style="color:#b3b3b3 !important;">Sun Tzu</span>',
  '“The weeds keep multiplying in our garden, which is our mind ruled by fear. Rip them out and call them by name.” <br/><span style="color:#b3b3b3 !important;">Sylvia Browne</span>',
  '“Imagination will often carry us to worlds that never were. But without it we go nowhere.” <br/><span style="color:#b3b3b3 !important;">Carl Sagan</span>',
  '“Believe in yourself! Have faith in your abilities! Without a humble but reasonable confidence in your own powers you cannot be successful or happy.” <br/><span style="color:#b3b3b3 !important;">Norman Vincent Peale</span>',
  '“Do you want to know who you are? Don’t ask. Act! Action will delineate and define you.” <br/><span style="color:#b3b3b3 !important;">Thomas Jefferson</span>',
  '“If you don’t design your own life plan, chances are you’ll fall into someone else’s plan. And guess what they have planned for you? Not much.” <br/><span style="color:#b3b3b3 !important;">Jim Rohn</span>',
  '“Live out of your imagination, not your history.” <br/><span style="color:#b3b3b3 !important;">Stephen Covey</span>',
  '“We have to continually be jumping off cliffs and developing our wings on the way down.” <br/><span style="color:#b3b3b3 !important;">Kurt Vonnegut</span>',
  '“Don’t be satisfied with stories, how things have gone with others. Unfold your own myth.” <br/><span style="color:#b3b3b3 !important;">Rumi</span>',
  '“Others have seen what is and asked why. I have seen what could be and asked why not.” <br/><span style="color:#b3b3b3 !important;">Pablo Picasso</span>',
  '“Imagination is everything. It is the preview of life’s coming attractions.” <br/><span style="color:#b3b3b3 !important;">Albert Einstein</span>',
  '“The worst enemy to creativity is self-doubt.” <br/><span style="color:#b3b3b3 !important;">Sylvia Plath</span>',
  '“To be creative means to be in love with life. You can be creative only if you love life enough that you want to enhance its beauty, you want to bring a little more music to it, a little more poetry to it, a little more dance to it.” <br/><span style="color:#b3b3b3 !important;">Osho</span>',
  '“You can’t use up creativity. The more you use, the more you have.” <br/><span style="color:#b3b3b3 !important;">Maya Angelou</span>',
  '“Creativity is allowing yourself to make mistakes. Art is knowing which ones to keep.” <br/><span style="color:#b3b3b3 !important;">Scott Adams</span>',
  '“Every child is an artist, the problem is staying an artist when you grow up.” <br/><span style="color:#b3b3b3 !important;">Pablo Picasso</span>',
  '“If you hear a voice within you say, ‘You cannot paint,’ then by all means paint, and that voice will be silenced.” <br/><span style="color:#b3b3b3 !important;">Vincent Van Gogh</span>',
  '“Have no fear of perfection, you’ll never reach it.” <br/><span style="color:#b3b3b3 !important;">Salvador Dali</span>',
  '“Curiosity about life in all of its aspects, I think, is still the secret of great creative people” <br/><span style="color:#b3b3b3 !important;">Leo Burnett</span>',
  '“You can’t wait for inspiration, you have to go after it with a club” <br/><span style="color:#b3b3b3 !important;">Jack London</span>',
  '“Imagination is the beginning of creation. You imagine what you desire, you will what you imagine, and at last, you create what you will” <br/><span style="color:#b3b3b3 !important;">George Bernard Shaw</span>',
  '“Don’t think. Thinking is the enemy of creativity. It’s self-conscious, and anything self-conscious is lousy. You can’t try to do things. You simply must do things” <br/><span style="color:#b3b3b3 !important;">Ray Bradbury</span>',
  '“To get the truth, you want to get your own heart to pound while you write.” <br/><span style="color:#b3b3b3 !important;">Robert McKee</span>',
  '“Each moment of our life, we either invoke or destroy our dreams.” <br/><span style="color:#b3b3b3 !important;">Stuart Wilde</span>',
  '“I don’t wait for moods. You accomplish nothing if you do that. Your mind must know it has got to get down to work.” <br/><span style="color:#b3b3b3 !important;">Pearl S. Buck</span>',
  '“Vulnerability is the birthplace of innovation, creativity and change.” <br/><span style="color:#b3b3b3 !important;">Brené Brown</span>',
  '“Knowing yourself is the beginning of all wisdom.” <br/><span style="color:#b3b3b3 !important;">Aristotle</span>',
  '“Until you make the unconscious conscious, it will direct your life and you will call it fate.” <br/><span style="color:#b3b3b3 !important;">Carl Jung</span>',
  '“And you? When will you begin that long journey into yourself?” <br/><span style="color:#b3b3b3 !important;">Rumi</span>',
  '“Your visions will become clear only when you can look into your own heart. Who looks outside, dreams; who looks inside, awakes.” <br/><span style="color:#b3b3b3 !important;">Carl Jung</span>',
  '“I am not what happened to me, I am what I choose to become.” <br/><span style="color:#b3b3b3 !important;">Carl Jung</span>',
  '“Where wisdom reigns, there is no conflict between thinking and feeling.” <br/><span style="color:#b3b3b3 !important;">Carl Jung</span>',
  '“The Secret of getting ahead is getting started.” <br/><span style="color:#b3b3b3 !important;">Mark Twain</span>',
  '“I never could have done what I have done without the habits of punctuality, order, and diligence, without the determination to concentrate myself on one subject at a time.” <br/><span style="color:#b3b3b3 !important;">Charles Dickens</span>',
  '“One finds limits by pushing them.” <br/><span style="color:#b3b3b3 !important;">Herbert Simon</span>',
  '“Concentrate all your thoughts upon the work at hand. The sun’s rays do not burn until brought to a focus.” <br/><span style="color:#b3b3b3 !important;">Alexander Graham Bell</span>'
];

Template.inspirationals.helpers({
  randomquote: function() {
    return Random.choice(quotes);
  }
})
