export default [
  { id: "achebe", name: "Chinua Achebe" },
  { id: "adams", name: "Douglas Adams" },
  { id: "ali", name: "Muhammad Ali" },
  { id: "angelou", name: "Maya Angelou" },
  { id: "arendt", name: "Hannah Arendt" },
  { id: "baldwin", name: "James Baldwin" },
  { id: "barnes", name: "Djuna Barnes" },
  { id: "beauvoir", name: "Simone de Beauvoir" },
  { id: "beckett", name: "Samuel Beckett" },
  { id: "christie", name: "Agatha Christie" },
  { id: "dali", name: "Salvador Dali" },
  { id: "dostoyevsky", name: "Fyodor Dostoyevsky" },
  { id: "earhart", name: "Amelia Earhart" },
  { id: "gordimer", name: "Nadine Gordimer" },
  { id: "hemingway", name: "Ernest Hemingway" },
  { id: "huxley", name: "Alduous Huxley" },
  { id: "joyce", name: "James Joyce" },
  { id: "jung", name: "Carl Jung" },
  { id: "kafka", name: "Franz Kafka" },
  { id: "kahlo", name: "Frida Kahlo" },
  { id: "kerouac", name: "Jack Kerouac" },
  { id: "lee", name: "Harper Lee" },
  { id: "lennon", name: "John Lennon" },
  { id: "marquez", name: "Gabriel García Márquez" },
  { id: "nin", name: "Anaïs Nin" },
  { id: "orwell", name: "George Orwell" },
  { id: "nietzsche", name: "Friedrich Nietzsche" },
  { id: "plath", name: "Sylvia Plath" },
  { id: "rand", name: "Ayn Rand" },
  { id: "rich", name: "Adrienne Rich" },
  { id: "salinger", name: "J. D. Salinger" },
  { id: "steinbeck", name: "John Steinbeck" },
  { id: "suyin", name: "Han Suyin" },
  { id: "thoreau", name: "Henry David Thoreau" },
  { id: "tolkien", name: "J. R. R. Tolkien" },
  { id: "tolstoy", name: "Leo Tolstoy" },
  { id: "tupac", name: "Tupac Shakur" },
  { id: "vonnegut", name: "Kurt Vonnegut" },
  { id: "watts", name: "Alan Watts" },
  { id: "weil", name: "Simone Weil" },
  { id: "whitman", name: "Walt Whitman" },
  { id: "woolf", name: "Virginia Woolf" },
];
